### ISSUE TITLE
Fazer a página de Home 

### ISSUE THREAD

**Issue by oraphaBorges** [RafaelMarangoni/sistema_bancario#123]
Fazer o esqueleto e estilização da página home, como referência o modelo passado para gente em aula, que seja o comportamento nosso sistema.

O Front-end deve ficar na branch `front` que será "deployada" pelo Netlify

**Comment by letcamara** [comment]
Home finalizada. Coloquei na pasta "**HomeModule**" só para não causar nenhum conflito por ora
