### ISSUE TITLE
Fazer página da Dashboard

### ISSUE THREAD

**Issue by oraphaBorges** [RafaelMarangoni/sistema_bancario#127]
Fazer o esqueleto e estilização da página da dashboard, como referência o modelo passado para gente em aula, que seja o comportamento nosso sistema, contendo

- [x] saldo da conta corrente
- [ ] saldo da conta poupança
- [x] saldo da conta crédito

e outros componentes que achar pertinente para funcionalidade

O Front-end deve ficar na branch `front` que será "deployada" pelo Netlify

**Comment by Evictory** [comment]
Dashboard finalizado. Necessário verificar os links que serão responsáveis por realizar os redirecionamentos
