### ISSUE TITLE
Fazer página de Extrato

### ISSUE THREAD

**Issue by oraphaBorges** [RafaelMarangoni/sistema_bancario#128]
Fazer o esqueleto e estilização da página home, como referência o modelo passado para gente em aula, que seja o comportamento nosso sistema, que:

- [x] tenha o campo de data de início
- [x] tenha o campo de data de fim

O Front-end deve ficar na branch `front` que será "deployada" pelo Netlify

**Comment by Evictory** [comment]
Criada página de extrato, bem como link para voltar a página anterior.
