### ISSUE TITLE
Fazer página de transação

### ISSUE THREAD

**Issue by oraphaBorges** [RafaelMarangoni/sistema_bancario#130]
Fazer o esqueleto e estilização da página home, como referência o modelo passado para gente em aula, que seja o comportamento nosso sistema, que seja possível fazer: 

- [x] pagamento
- [x] depósito
- [x] transação

O Front-end deve ficar na branch `front` que será "deployada" pelo Netlify

**Comment by letcamara** [comment]
Página de transações feita. Basicamente aproveitei a página de dashboard e fiz 3 cards com as funções de: Pagamento, Depósito  e Transferência. Foi criado uma novo estilo para essa página: transactions.css
