### ISSUE TITLE
Entrega JS

### ISSUE THREAD

**Issue by oraphaBorges** [RafaelMarangoni/sistema_bancario#145]
Criar o arquivo JS com todas as requisições para a [nossa](https://gama-bankline-desbugados.herokuapp.com/) API e a API disponibilizada pelo [prof. Gleyson](https://accenture-java-desafio.herokuapp.com/swagger-ui.html#/), na dúvida consultar os [Swagger](https://gama-bankline-desbugados.herokuapp.com/swagger-ui.html#) para conferir as rotas.

Obs: lembrando de fazer o `local storage` do token e uma função para requisição e o `console.log(response.data)` para mostrar o retorno e garantia de a requisição está funcionando.

Obs: Se não me engano a request tem q ser feita com o `fetch`, mas por garantia e se não foi muito trabalho, fazer com o `fetch` e `axios`.

**Comment by Evictory** [comment]
Por orientação e confirmação do professor, optamos por realizar dois métodos: cadastro de usuários e realização do login. 

Para isso foi criada uma classe UserService - responsável pelas requisições, bem como um script.js - responsável pela captura dos eventos e consumação da UserService.

Tudo foi criado e testado, e o deploy está no seguinte link: 

https://desbugados-gama2.netlify.app/
