### ISSUE TITLE
DashboardService - Realizar lançamento

### ISSUE THREAD

**Issue by Evictory** [RafaelMarangoni/sistema_bancario#165]
Criar, em DashboardService, o método para realizar um lançamento

Realizar a função utilizando objeto estático e utilizar o console.log  para exibir os dados retornados.

Utilizar o endpoint: /lancamentos

Informações: https://accenture-java-desafio.herokuapp.com/swagger-ui.html#/

**Comment by letcamara** [comment]
Criei, em DashboardService, o método para realizar um lançamento. Para teste, criei um objeto estático (**transaction**)
