### ISSUE TITLE
DashboardService - Criar plano de conta

### ISSUE THREAD

**Issue by Evictory** [RafaelMarangoni/sistema_bancario#166]
Criar, em DashboardService, o método para realizar a criação de um plano de conta.

Realizar a função utilizando objeto estático e utilizar o console.log  para exibir os dados retornados.

endpoints: https://accenture-java-desafio.herokuapp.com/swagger-ui.html#/

**Comment by letcamara** [comment]
Criei, em DashboardService, o método para realizar a criação de um plano de conta. Foi criado um objeto com o nome de "transactionAccount" de forma estática.
