### ISSUE TITLE
DashboardService - Buscar planos de conta

### ISSUE THREAD

**Issue by Evictory** [RafaelMarangoni/sistema_bancario#167]
Criar, em DashboardService, o método para buscar os planos de conta existentes.

Realizar a função utilizando objeto estático e utilizar o console.log  para exibir os dados retornados.

Informações: https://accenture-java-desafio.herokuapp.com/swagger-ui.html#/

**Comment by letcamara** [comment]
Criei, em DashboardService, o método "getPlanAccount" que busca os planos de conta existentes do usuário logado.
