### ISSUE TITLE
Criar HTML Componete Dashboard

### ISSUE THREAD

**Issue by oraphaBorges** [RafaelMarangoni/sistema_bancario#172]
Estilizar e incluir os html das páginas, de acordo com o que foi feito anteriormente no projeto. Lembrando que nessa pagina deve haver os seguintes componentes: 
- [x] HeaderDash: com msg de boas vindas, data atual, botão de atualizar e sair
- [ ] Componente de card com os dados do usuario (nome completo) 
- [ ] Componente de card para a conta CREDITO com o saldo da conta, os últimos 3 lançamento e link para extrato completo
- [ ] Componente de card para a conta POUPANÇA com o saldo da conta, os últimos 3 lançamento e link para extrato completo
- [ ] Componente de card para a conta CORRENTE com o saldo da conta, os últimos 3 lançamento e link para extrato completo

obs: não utilizar o bootstrap.

**Comment by Evictory** [comment]
Criado um header genérico para utilização em todos os componentes

**Comment by Evictory** [comment]
A estilização e estrutura foi realizada de acordo com o anterior, mas passível de migração /refactor para utilização da nossa api.

**Comment by Evictory** [comment]
Refatorado e populado.
