### ISSUE TITLE
Criar HTML de Extrato

### ISSUE THREAD

**Issue by oraphaBorges** [RafaelMarangoni/sistema_bancario#175]
Estilizar e incluir os html das páginas, de acordo com o que foi feito anteriormente no projeto. Lembrando que nessa pagina deve haver os seguintes componentes: 
- [ ] HeaderTransacao: com msg avisando q aquela é onde solicita o extrato, data atual, botão de atualizar e sair
- [ ] Componente de card para solicitação do extrato com o campo para pegar a data de início e fim e o botão para solicitar o extrato
- [ ] Componente de card com a listagem dos lançamentos pegos pelo extrato

obs: não utilizar o bootstrap.

**Comment by letcamara** [comment]
Criei o HTML da página de Extrato e inseri a página Extract.js. Por estar com dificuldades em encontrar propriedades como: box-sizing e width: 100% sozinhas - coloquei esses elementos no código **inline**. Sei que se trata de uma má prática, porém, irei entender melhor em como inserir novas propriedades de css ao código.
