### ISSUE TITLE
Criar HTML do componente Menu do Dashboard

### ISSUE THREAD

**Issue by oraphaBorges** [RafaelMarangoni/sistema_bancario#176]
Criar o html do menu fixo lateral (em tela cheia) / inferior (em tela pequena) do Dashboard que deve conter os botões para transitar entre as funções da dashboard: 

- [x] Home
- [x] Transações
- [x] Extrato
- [x] Planos de Conta

**Comment by Evictory** [comment]
Componente criado nas duas modalidades!
