### ISSUE TITLE
Relacionar a entidade Usuário à Conta

### ISSUE THREAD

**Issue by oraphaBorges** [RafaelMarangoni/sistema_bancario#19]
Criar a relação entre a entidade Usuário e Conta como OneToMany, pois um usuário pode ter diversos tipo diferentes de contas.

**Comment by RafaelMarangoni** [comment]
Realizei o relacionamento entre as tabelas, porem nao é criada uma tabela de referencia em tb_usuario, e criada apenas na conta, referenciando o usuario, isso está correto ?
