### ISSUE TITLE
Implementar DTO para BuscarSaldo

### ISSUE THREAD

**Issue by oraphaBorges** [RafaelMarangoni/sistema_bancario#38]
Utilizar das praticas de [DTO](https://pt.stackoverflow.com/questions/31362/o-que-%C3%A9-um-dto) para as implementações das regra de negocio pensando em passar o minimo de parâmetros possíveis entre chamadas de métodos.

**Comment by oraphaBorges** [comment]
Para mais referencias de [DTO](https://medium.com/@msealvial/blindando-sua-api-spring-boot-com-o-padr%C3%A3o-dto-44f97020d1a0)

**Comment by Evictory** [comment]
Necessário implementar o spring web antes da implementação. Classe base já criada

**Comment by Evictory** [comment]
Conforme visto [aqui,](https://accenture-java-desafio.herokuapp.com/swagger-ui.html#/) é necessário inclur os lançamentos no DTO.

**Comment by Evictory** [comment]
Como vamos partir das tasks de resources, alterei essa issue para refatorar a função buscarSaldo da classe de Contas
