### ISSUE TITLE
Refatorar o projeto para Spring Data JPA

### ISSUE THREAD

**Issue by oraphaBorges** [RafaelMarangoni/sistema_bancario#39]
Fazer a conversão da persistência com JPA, para fazer a persistência com Spring Data JPA
- [x] Inclusão das dependências
- [ ] Configs do `properties` para passar o parâmetros de conexão com o mysql
- [ ] mudar os `repositories` para implementar o CRUDrepository, query methods e `anotations`
- [x] criar o pacote `resource` para a criação dos endpoints da API

**Comment by RafaelMarangoni** [comment]
Todo JPA e repository estão prontos para uso, adicionei novas dependencias no POM (validation e Spring Tools)
