### ISSUE TITLE
Criar classe que monitora data de inserção e de atualização

### ISSUE THREAD

**Issue by Evictory** [RafaelMarangoni/sistema_bancario#44]
Aqui segue um modelo de classe para implementação:

https://github.com/Evictory/bankline/blob/main/src/main/java/model/DateUseful.java

Essa classe será injetada em todas as entidades via anotação. Assim teremos uma data de inserção e de atualização (caso ocorram) de todos os objetos que serão persistidos.

- [x] Criar classe modelo
- [x] Injetar embedded na classe Conta
- [x] Injetar embedded na classe Lançamento
- [ ] Injetar embedded na classe PlanoConta
- [ ] Injetar embedded na classe Usuario

**Comment by oraphaBorges** [comment]
Criado do DataUseful como Registro e ao invés de `created_on` ou `uptadated_on`, ficou `created_at` e `updated_at` pois gramaticalmente para horários, a preposição "at" refere-se algo mais pontual e preciso.
