### ISSUE TITLE
Incluir dependência do Spring Web

### ISSUE THREAD

**Issue by Evictory** [RafaelMarangoni/sistema_bancario#47]
Incluir a dependência do Spring web na branch java_28 para podermos realizar as implementações dos serviços REST.

- [x] Incluir dependência no pom.xml
- [x] Realizar teste de acesso ao projeto via localhost

**Comment by oraphaBorges** [comment]
Transformado o projeto em um spring boot aplicando e testando as dependências do spring boot e web.
Obs: pode ser que ele reclame do 	`@Column(nullable = false) private LocalDate dataLancamento;` na entidade Lançamento, mas aí é só comentar, subir, descomentar e subir a aplicação novamente que se resolve.

Obs2: o aquivo `target/classes/application.properties` que vai conter as info do banco e tudo mais, está no gitignore e por isso tem o aquivo `target/classes/application.axample.properties` para ser usado como referencia para cada um criar o seu de acordo com os dados local de acesso ao banco de dados.

**Comment by Evictory** [comment]
@oraphaBorges quando mergear no repo principal, sinta-se à vontade para fechar a issue ou me avisar :)

**Comment by oraphaBorges** [comment]
foi feito o merge já.

**Comment by Evictory** [comment]
Tinha visto a branch errada rs. Achei que estivesse esperando algo. Nice done
