### ISSUE TITLE
Criar a classe UsuarioDTO

### ISSUE THREAD

**Issue by Evictory** [RafaelMarangoni/sistema_bancario#50]
Utilizar das praticas de [DTO](https://pt.stackoverflow.com/questions/31362/o-que-%C3%A9-um-dto) para as futuras implementações das regras de negocio pensando em passar o minimo de parâmetros possíveis entre chamadas de métodos.

[Aqui](https://accenture-java-desafio.herokuapp.com/swagger-ui.html#/) segue um exemplo dos atributos esperados

A implementação será realizada em uma outra issue.

Branch: Java_28

**Comment by oraphaBorges** [comment]
criado a classe do UsuarioDTO como LoginDTO

**Comment by Evictory** [comment]
criado a classe do UsuarioDTO.

O DTO de login utilizaremos para os logins efetivamente e o de Usuario para criação de usuários em si
