### ISSUE TITLE
Converter PlanoContaService em um service do Spring

### ISSUE THREAD

**Issue by oraphaBorges** [RafaelMarangoni/sistema_bancario#72]
Converter PlanoContaService em um service do Spring com os os métodos de CRUD e metodos de busca que chamam o PlanaContaRepository para fazer a persistência:
- [x] **CR** - cadastrar
- [x] **U** - atualizar
- [x] **D** - deletar
- [x] buscas

**Comment by Evictory** [comment]
O crud completo foi realizado, bem como funções de validação genéricas, aplicadas a todos os métodos. Como de validação se o usuário existe antes de realizar operações.

Quanto a busca por login, foi implementada uma genérica que retorna todos os planos de contas cadastrados para um login previamente informado.
