### ISSUE TITLE
Refatorar os Resources

### ISSUE THREAD

**Issue by oraphaBorges** [RafaelMarangoni/sistema_bancario#75]
Fazer com que TODOS os Resources sigam esse padrão:
- [x] @ResquestMapping("/api")
- [x] Todas as chamas de persistência devem chamar um Service e nunca um Repository (se necessário, implementar no service o método desejado)
- [x] Sempre passar um DTO para as chamadas dos Repository
- [x] Os Resources devem contar ops Endpoints para CRUD
- [x] Sempre retornar um DTO paras os Endpoints que solicitam dados
- [x] Estar atento ao [HTTP STATUS](https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Status) correto para a operação

**Comment by Evictory** [comment]
Para o item 1, podemos adicionar no arquivo application.properties o seguinte conteúdo:

server.servlet.contextPath=/api

Ou podemos criar a classe depois, mas não é considerado adequado, já que o Spring já lida com isso. [Veja aqui](https://stackoverflow.com/questions/28006501/how-to-specify-prefix-for-all-controllers-in-spring-boot) um exemplo,
